export const users=[
  {
    id:1,
    role:'admin',
    firstname:'amine',
    lastname:'serra',
    email:"amine.serra@hotmail.fr",
    password:"Azerty0.",
    avatar:"avatar_default.jpg",   
  },
  {
    id:2,
    role:'joueur',
    firstname:'romain',
    lastname:'doe',
    email:"romain.doe@hotmail.fr",
    password:"Azerty1.",
    avatar:"avatar_default.jpg",   
  },
  {
    id:3,
    role:'supporter',
    firstname:'john',
    lastname:'doe',
    email:"john.doe@hotmail.fr",
    password:"Azerty2.",
    avatar:"avatar_default.jpg",   
  }
]