export const users=[
  {
    id:1,
    role:'admin',
    firstname:'amine',
    lastname:'serra',
    emailLogin:"amine.serra@hotmail.fr",
    passwordLogin:"Azerty0.",
    avatar:"avatar_default.jpg",   
  },
  {
    id:2,
    role:'joueur',
    firstname:'romain',
    lastname:'doe',
    emailLogin:"romain.doe@hotmail.fr",
    passwordLogin:"Azerty1.",
    avatar:"avatar_default.jpg",   
  },
  {
    id:3,
    role:'supporter',
    firstname:'john',
    lastname:'doe',
    emailLogin:"john.doe@hotmail.fr",
    passwordLogin:"Azerty2.",
    avatar:"avatar_default.jpg",   
  }
]